# Power law fits for density ~ biomass.
# BCI and Harvard
# QDR 3 Mar 2017

source('~/GitHub/forestlight/code/mergeshade.r')

pdat <- dat %>% 
  mutate(biomass3 = pmax(BiomassDGH_year3_kg, BiomassDBH_year3_kg, na.rm=TRUE),
         biomass2 = pmax(BiomassDGH_year2_kg, BiomassDBH_year2_kg, 0, na.rm=TRUE),
         biomass1 = pmax(BiomassDGH_year1_kg, BiomassDBH_year1_kg, 0, na.rm=TRUE),
         massprod23 = pmax(biomass3 - biomass2, 0, na.rm=TRUE),
         massprod12 = pmax(biomass2 - biomass1, 0, na.rm=TRUE),
         massprod13 = pmax((biomass3 - biomass1)/2, 0, na.rm=TRUE)) %>% 
  select(Site, biomass3, biomass2, massprod23, massprod12, massprod13, CII, tolerance)
bcidat <- pdat %>% filter(Site == 'Barro_Colorado_Island', !is.na(CII), !is.na(biomass3))
harvdat <- pdat %>% filter(Site == 'Harvard_Forest_LTER', !is.na(CII), !is.na(biomass3))

# Calculate MLE of parameters of power law distribution.
# Only use trees that John measured CII on.
# Use biomass in year 3

library(poweRlaw)

# BCI
pl_bci <- conpl$new(bcidat$biomass3) # Create continuous power law object.
pl_bci$getXmin() # Display xmin parameter.
pars_bci <- estimate_pars(pl_bci)

# Estimate xmin
est_bci <- estimate_xmin(pl_bci)
pl_bci$setXmin(est_bci) # Set power law object to optimal values generated by est_bci (both xmin and alpha are estimated from the data)

# Bootstrap confidence intervals around parameters
boot_pl_bci <- bootstrap(pl_bci, no_of_sims = 999, threads = 3) # Expected run time is ~ 1 hour!

# Harvard Forest
pl_harv <- conpl$new(harvdat$biomass3)
est_harv <- estimate_xmin(pl_harv) # This appears to be problematic.
pl_harv$setXmin(est_harv)

pars_harv <- estimate_pars(pl_harv)
pl_harv$setPars(pars_harv)
plot(pl_harv)

boot_pl_harv <- bootstrap(pl_harv, no_of_sims = 999, threads = 3)

######
# Run similar density ~ mass fit as above, but split by shade tolerance class
pl_bci_shade <- conpl$new(na.omit(bcidat$biomass3[bcidat$tolerance == 'S']))
est_bci_shade <- estimate_xmin(pl_bci_shade)
pl_bci_shade$setXmin(est_bci_shade)

pars_bci_shade <- estimate_pars(pl_bci_shade)
pl_bci_shade$setPars(pars_bci_shade)

plot(pl_bci_shade)

pl_bci_int <- conpl$new(na.omit(bcidat$biomass3[bcidat$tolerance == 'I']))
est_bci_int <- estimate_xmin(pl_bci_int)
pl_bci_int$setXmin(est_bci_int)

plot(pl_bci_int)

pl_bci_gap <- conpl$new(na.omit(bcidat$biomass3[bcidat$tolerance == 'G']))
est_bci_gap <- estimate_xmin(pl_bci_gap)
pl_bci_gap$setXmin(est_bci_gap)

plot(pl_bci_gap)

######
# Use massprod13 to create log bins. Fit power law to them.
# Also fit linear function to them.
# Split them by shade tolerance class.

